### ISSUE TITLE
Add global option to turn off all reminders

### ISSUE THREAD

**Issue by dar5hak** [elfenware/badger#1]
Could be a switch next to the **Reminders** heading

**Comment by siigdev** [comment]
Would be great!
Furthermore, for me, it would also be very helpful if it could detect if the user is actually active on the PC (I don't know if that's even possible. Would require a lot I guess), as my PC is always running and keeps receiving those notifications even when I'm not around. If not, then maybe the ability to turn it off in certain time periods?

However, I guess that's not a struggle many people has, and it should probabily be lowest priority. But I'm just throwing it out there :)

**Comment by dar5hak** [comment]
> detect if the user is actually active on the PC

There was some discussion about this in #4 but I don't think there's a straightforward way to do it. I mean, when I resume my laptop after a suspend, it still shows me the stale notification about when WiFi was disconnected while suspending. And that's an OS feature. :sweat_smile:

> the ability to turn it off in certain time periods

Would be nice to have, but till we get around to it, you can always use the elementary OS notification settings and tell it to not save Badger notifications to Notification Center.

I personally don't think there's much sense in Badger notifications being retained for later, but that's not something an app can control directly. It's a user preference.
