### ISSUE TITLE
Is the 256x256 icon necessary?

### ISSUE THREAD

**Issue by NathanBnm** [elfenware/badger#17]
The elementary HIG only recommends from 16x16 to 128x128, what's the point?

**Comment by dar5hak** [comment]
[Develop](https://appcenter.elementary.io/com.github.alcadica.develop) added it for me when I generated a scaffold. I'm not sure, but I think it may be needed when displaying a 128x128 icon at 2x density on HiDPI displays.

**Comment by NathanBnm** [comment]
Maybe you're right, I'm going to investigate on this 👍

**Comment by dar5hak** [comment]
Thanks! Feel free to reopen this if you find something.

**Comment by NathanBnm** [comment]
Yes sure! 😊
