### ISSUE TITLE
Don't manually break lines in appdata

### ISSUE THREAD

**Issue by danrabbit** [elfenware/badger#2]
They render in AppCenter as line breaks:

![Screenshot from 2019-03-09 17 23 27@2x](https://user-images.githubusercontent.com/7277719/54079373-2da4a700-4290-11e9-8745-f5273b27ba3f.png)

**Comment by dar5hak** [comment]
Ah, I see… thanks! My brain was in browser mode! :sweat_smile: 

Fixed in v1.0.2.
