### ISSUE TITLE
Notification control

### ISSUE THREAD

**Issue by nathanaelhoun** [elfenware/badger#34]
When a notification pop out, I look away my screen, and when I come back, the notification is gone but not really : it's still in the notification center. As I can't turn off the notification center feature for all the "others" apps, it would be really handy if Badger was known by the system-wide notification system. I found out that adding `X-GNOME-UsesNotifications=true` in the `.desktop` file enable something like this, which is exactly what I needed. 
![Screenshot from 2019-10-23 19-25-56](https://user-images.githubusercontent.com/45119518/67418397-fc80a900-f5ca-11e9-976e-7b74a7a9e411.png)
What are you thoughts ?

**Comment by dar5hak** [comment]
@nathanaelhoun Whoa, I actually remember wanting to do the exact same thing a few months ago, but did not try to find out how. This is perfect. Thank you!
