### ISSUE TITLE
add strict eye protection 

### ISSUE THREAD

**Issue by minutesinch** [elfenware/badger#50]
you can add an enhancement when eye relax time is coming in 5 second, the transparent black window appear with full screen sized to avoid user look.

**Comment by dar5hak** [comment]
Hmm, interesting idea. Will have to see how to implement this.

Also, if added, this would be opt-in. Can't suprise a user who might be focusing or watching a video.

**Comment by minutesinch** [comment]
thank you, yes and yes you must add warn before relax time

**Comment by dar5hak** [comment]
Decided not to implement this for reasons stated in #58.
