### ISSUE TITLE
Incorrect 4.2.0 release date

### ISSUE THREAD

**Issue by cassidyjames** [elfenware/badger#69]
Something I noticed when doing a review:

https://github.com/elfenware/badger/blob/6737ae3423446dd94cd8c677362c7ce7704d85dd/data/com.github.elfenware.badger.appdata.xml.in#L28
 
Versus the release on 2021-08-28 https://github.com/elfenware/badger/releases/tag/v4.2.0

**Comment by dar5hak** [comment]
Huh. Why would I type that?

Thanks for pointing out.
