### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by Arnwaltur** [elfenware/badger#71]
Hello,

I find my locale translation in repo (french) but app and notification still display in english.

System : eOS 6 Odin
cat /etc/default/locale : LANG=fr_FR.UTF-8

**Comment by dar5hak** [comment]
Huh. No idea why that would happen. Does the rest of the UI get rendered in French?

@NathanBnm do you have any ideas?

**Comment by NathanBnm** [comment]
@Arnwaltur @dar5hak I'll check it out asap

**Comment by Arnwaltur** [comment]
@dar5hak @NathanBnm The rest of the UI is rendered in French, and another application (Reminduck) from eOS AppCenter is also rendered in French.

**Comment by dar5hak** [comment]
@Arnwaltur Sorry, I haven't been able to check this. Will give it a shot later today.

**Comment by dar5hak** [comment]
Okay, I wasn't able to reproduce this. I ran Badger v4.2.0 with French:

```sh
LANGUAGE=fr_FR.UTF-8 com.github.elfenware.badger
```

Then I turned down the duration to one minute. One minute later, the notification appeared in French.

@Arnwaltur what version of Badger do you have installed?

**Comment by Arnwaltur** [comment]
Badger v4.2.0 with Elementary 6.

I reinstalled several times without success. 
Then I searched the Flatpak folder to see.
.local/share/flatpak/app/com.github.elfenware.badger/

The language folders in share/runtime/locale/ are all empty.

Hope this helps.

**Comment by dar5hak** [comment]
Thanks, let me see what's going on there.

**Comment by dar5hak** [comment]
Still not finding anything. I checked my `share/runtime/locale` and the locales are there. And even if they're not there in your machine, it's weird that they would render parts of the application in French.

@NathanBnm if/when you have time, could you help out? My localization knowledge is very limited, so I'm shooting in the dark here.

**Comment by NathanBnm** [comment]
@dar5hak I'll check this out on my side

**Comment by Arnwaltur** [comment]
I tried to purge all local installation folders and then reinstall from AppCenter without success. Finally, installing from source, the translation applies.

**Comment by dar5hak** [comment]
In that case, the issue could be with Flatpak rather than in Badger core.

@Arnwaltur did you use Badger back in the 5.x days? Did it work correctly there?

**Comment by Arnwaltur** [comment]
No, only since the 6th.

**Comment by dar5hak** [comment]
I don't think it is related.

> But the application specific strings remain untranslated.

If this were the case, you would not see any of the strings in French, including the ones inside the window. And that would be the case for everyone using the Flatpak, including Nathan and me.
